### ISSUE TITLE
Option not to touch files with earlier date/time

### ISSUE THREAD

**Issue by wpwoodjr** [MestreLion/git-tools#49]
Thanks for the git-restore-mtime tool!

I think it would be useful if files with earlier date/times than the commit time could be skipped.  That way the original file date/time history for files that are in the original source directory they came from could be preserved.

**Comment by MestreLion** [comment]
You're welcome, glad it's been useful, and sorry for taking so long to look more carefully into this.

This is an interesting feature, even if kinda of defeats the use-case of "normalizing" timestamps, it has a valid use case by itself.

The problem is: while apparently similar to `--skip-older-than`, this one is deceptively harder to implement _properly_: `--skip-older-than` operates by filtering the input file list, so there's no performance penalty in the most time-sensitive log parsing inner loop. On the other hand, this `--skip-older-than-commit` (is that a good name btw?) _requires_ a per-file decision inside the inner loop, right before calling `touch()`.

Being the most time-sensitive tight loop, I try to be very conservative on what features I'll add there. And when I do, it's usually using an approach of pre-setting an appropriate `touch()` function override, so it has zero-penalty for runs without the option. That's the strategy used by `--test` (the dry-run) and `--unique-times`. It's a great approach performance-wise, but it doesn't scale well when you start needing to _nest_ them, such as combining `--unique-time`  with `--skip-older-than-commit`

That said, I'll try to figure out a way to implement this (it's a simple `if` afterall) in a way that has no impact for runs that do not use this option. If you have any ideas (or, better, a PR), I'm all ears!

**Comment by wpwoodjr** [comment]
I recently implemented this for `git-extras` [here](https://github.com/tj/git-extras/blob/master/bin/git-utimes).  I used `--newer` as the flag, but I think `--skip-older-than-commit` is more descriptive.  It's parallelized via `xargs`, so the inner loop runs pretty fast.

**Comment by MestreLion** [comment]
What a nice project this `git-extras`, wow! My new goal is to have a project structure like that, with `Makefile`, proper documentation and all that :) Maybe I'll just donate my lesser tools to that project so mine focus only on `git-restore-mtime`

I've suggested `--skip-older-than-commit` as I already have a `--skip-older-than SECS`, so it felt in-line with other options.

I took a look at `git-utimes`, it has some very nice ideas, specially on flags (`-z` being one in my backlog for ages). But the parallelization is _monumentally_ inefficient: If I'm reading correctly, it seems it is running `git log` for _each worker call_!  That's painfully slow, even in my 12-core CPU. 

I've tried experimenting with parallelization before, but the problem is: `git log` is a _**very**_ expensive call, no matter how you parse it. For any medium project, calling it more than _once_ is bound to be inefficient, let alone once per each group of 4-64 files. For large ones such as `git` or `wine` this is prohibitive, and I'm not even mentioning `homebrew-core` or `linux`

And, surprisingly, `touch` is _very_ cheap. So cheap that both `git-utimes` and `git-restore-mtime` are **not** IO-bound. They're CPU-bound! Just run `for file in $(git ls-files); do touch "$file"; done` and see how blazing fast it is.
```console
mestrelion@desktop ~/repos/wine $ find . -name '* *' | wc -l  # no paths with spaces, can use a naive loop
0
mestrelion@desktop ~/repos/wine $ touch-all(){ i=0; for file in $(git ls-files); do ((i++)); touch "$file";
> done; echo "$i files"; }
mestrelion@desktop ~/repos/wine $ flush(){ sync; echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null; }
mestrelion@desktop ~/repos/wine $ touch-all; flush; time { touch-all; sync; }
9399 files

real	0m12,303s
user	0m8,330s
sys	0m3,988s
mestrelion@desktop ~/repos/wine $ touch-all; flush; time { git-restore-mtime -v; sync; }
9399 files
9,399 files to be processed in work dir
...
Statistics:
         9.04 seconds
      740,455 log lines processed
      158,127 commits evaluated
        1,088 directories updated
        9,399 files updated

real	0m9,097s
user	0m3,793s
sys	0m0,539s

mestrelion@desktop ~/repos/wine $ touch-all; flush; time { git-utimes; sync; }
9399 files
...
real	12m54,007s
user	143m6,494s
sys	4m15,079s
```

So `xargs` parallelization has very little to offer, if any. And if not properly done it can _really_ plummet performance to a halt.

PS: I have **no** idea how a python script was able to be faster than a `for ... touch` loop, and I repeated this test many times, and it consistently is... if anyone has a clue why, please chime in!

**Comment by MestreLion** [comment]
That said, given how fast `git-restore-mtime` is, and that I just realized I'm blindly making costly calls such as `isodate()` in the inner loop even when not using `--verbose`, I believe `--skip-older-than-commit` will have a negligible impact even if implemented as `if args.skip_older_than_commit and os.path.getmtime(file): continue`.

So, considering that is a very useful feature and its gain far outweighs the cost, I'll surely add this before my next release this month :)

**Comment by wpwoodjr** [comment]
>But the parallelization is _monumentally_ inefficient: If I'm reading correctly, it seems it is running `git log` for _each worker call_! That's painfully slow, even in my 12-core CPU.

You're right... this is how it was originally written and I didn't try to optimize that.

**Comment by MestreLion** [comment]
Done! Care to help testing?

**Comment by wpwoodjr** [comment]
Sure

**Comment by wpwoodjr** [comment]
You probably can't do it, but I would like it if `--skip-older-than-commit` was the default.  The issue is, if you ever once forget to use the flag, the original dates are lost.

**Comment by MestreLion** [comment]
Yeah, I know. I also would prefer to set it as default. But forcing existing users to change/add a `--include-older-than-commit` to restore original behavior is a no-no

As a workaround, you could always add an alias to your `~/.bashrc`: `alias grm='git restore-mtime -N'

**Comment by wpwoodjr** [comment]
Can you just ignore files that are changed in the working directory (like `git-utimes` does), instead of aborting?

**Comment by MestreLion** [comment]
> Can you just ignore files that are changed in the working directory (like `git-utimes` does), instead of aborting?

Done in #51
