### ISSUE TITLE
Time zone support

### ISSUE THREAD

**Issue by Hentioe** [MestreLion/git-tools#73]
I use `git-restore-mtime.py` with the Hugo generator to restore an post's edit time from Git information. The effect is very good, great script👍.

But `git-restore-mtime.py` seems to restore UTC time, right? I added time zone to the system environment where this script is executed, but it had no effect.
Is it possible to add a time zone parameter to offset the time according to the user-specified time zone when setting the mtime of the file?

**Comment by MestreLion** [comment]
It restores to whatever time is in the commit metadata. `git` includes the local time zone when it stores timestamps, so if the commits were made in UTC, it will restore to the corresponding time in the filesystem. Changing the time zone of only the script execution environment will have no effect, as `restore-mtime` (and most filesystems) do not rely on the local time zone. However, if you change your _system's_ time zone, it will affect how the times are _presented_ to you.

For example, let's assume a commit made today at 6AM in Rio (that's BRT, which is UTC -3), being restored to an EXT4 filesystem (which stores dates as seconds since the [Unix Epoch](https://en.wikipedia.org/wiki/Unix_time)) in a system set to Moscow time (MSK, UTC +3):
- Git commit contains `2024-04-24 06:00:00 BRT`
- This is converted (by `git` itself) to the Unix Time of 1713949200, which is time-zone agnostic
- That is the timestamp set on the filesystem by `git-restore-mtime`, via `touch`
- When listing the file, with `ls` or in a File Manager, the _system_ reports the file's mtime as `2024-04-24 12:00:00 MSK`, as it was midday in Moskow when the file was committed in Rio.
- If you now change the system's local time to, say, California (currently on PDT, UTC -7), the file will be presented as `2024-04-24 02:00:00 PDT`

I hope this helps clarifying. Let me know if you still think a time offset option is useful, and how exactly would it work.

**Comment by Hentioe** [comment]
Thank you for your enthusiastic reply. My Git commit environment is time zoned but still reverted to UTC time. I will further test it when I have time to find out what the cause is. I will update this issue with the results, thank you.

**Comment by MestreLion** [comment]
What is the repository in question? Is it public? I might be able to take a look too

**Comment by Hentioe** [comment]
I have tested repeatedly and have determined that `git-restore-mtime` restores the time correctly. My problem has been solved and has nothing to do with `git-restore-mtime`. Thanks for your help and this very useful script 👍.

My project is a static website generated by Hugo. I use `git-restore-mtime` to restore the file modification time from Git information so that Hugo can generate the correct post editing time.
